### ISSUE TITLE
NullPointerException when using setBackgroundColor()

### ISSUE THREAD

**Issue by abhaybd** [mukeshsolanki/DrawingView-Android#12]
I'm trying to set the background color to black, but it throws a `NullPointerException`.

This is my code:

    DrawingView drawingView = (DrawingView) findViewById(R.id.scratch_pad);
    drawingView.initializePen();
    drawingView.setPenColor(Color.WHITE);
    drawingView.setBackgroundColor(Color.BLACK);

And this is the stacktrace:

    Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.graphics.Canvas.drawColor(int)' on a null object reference
                      at com.mukesh.DrawingView.setBackgroundColor(DrawingView.java:156)
                      at com.coolioasjulio.draw.MainActivity.onCreate(MainActivity.java:21)
                      at android.app.Activity.performCreate(Activity.java:6955)
                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1126)
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2927)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3045) 
                      at android.app.ActivityThread.-wrap14(ActivityThread.java) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1642) 
                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                      at android.os.Looper.loop(Looper.java:154) 
                      at android.app.ActivityThread.main(ActivityThread.java:6776) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410) 

I did some digging around, and it seems that `mCanvas` is null, resulting in a `NullPointerException`.

How can I fix this?

**Comment by mukeshsolanki** [comment]
Can you check the example app

**Comment by lampione** [comment]
I also have the same problem, plus I can't draw anything at all, it just doesn't draw even after selecting calling `initializePen()`

**Comment by ralucagurau** [comment]
I also have the same problem

**Comment by mukeshsolanki** [comment]
can one of you share a code example of the issue?

**Comment by mukeshsolanki** [comment]
Fixed in the latest version
